// <auto-generated />
namespace DREAM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CurrentSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrentSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201303072119078_IntialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
