// <auto-generated />
namespace DREAM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddGender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGender));
        
        string IMigrationMetadata.Id
        {
            get { return "201303112347175_AddGender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
