// <auto-generated />
namespace DREAM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateGroupTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateGroupTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201303171737204_CreateGroupTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
